### ISSUE TITLE
Example program fpm overloading CPUs

### ISSUE THREAD

**Issue by Chadster766** [OpenFastPath/ofp#11]
```
top - 05:02:02 up 27 min,  1 user,  load average: 3.92, 3.93, 3.32
Tasks:  71 total,   2 running,  69 sleeping,   0 stopped,   0 zombie
%Cpu(s): 58.7 us, 41.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:    251820 total,   203292 used,    48528 free,     4772 buffers
KiB Swap:        0 total,        0 used,        0 free.   123632 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2500 root      20   0  188456  76680  76448 S 197.7 30.5  53:37.07 fpm
 3955 root      20   0    2972   1720   1364 R   0.7  0.7   0:00.05 top
    7 root      20   0       0      0      0 R   0.3  0.0   0:05.00 rcu_sched
 2941 root      20   0    4696   2276   1968 S   0.3  0.9   0:06.79 hostapd
    1 root      20   0    5036   3516   2100 S   0.0  1.4   0:03.45 systemd
```

**Comment by ikoveshnikov** [comment]
Hi,

That is normal behaviour for 'top' utility. By default, 100% in 'top' means that one single core is fully loaded, so ~200% in your case  means that 2 cores occupied with 'fpm' almost all the time.

Try to press 'Shift + i' to show overall load. Other way is to use 'htop' instead of 'top'

Anyway, 100% CPU load is expected behaviour for most of the ODP implementations: instead of sleeping and waiting for incoming packets, we are constantly polling pktio devices to get packets from them. Such approach is very common for userspace networking, it brings the highest speeds and smallest latencies. But price is high CPU consumption.

**Comment by Chadster766** [comment]
Thanks explaining the process. :smile:

**Comment by semihalf-berestovskyy-andriy** [comment]
Note: the comment was created automatically with bugzilla2github tool

---
**Bugzilla bug ID:  11**
**Renumbered to issue: #134**
