### ISSUE TITLE
Nexthops may be used after freed and while being modified

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#120]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 120
Date: 2017-01-16 11:02:07 +0100
From: janne.peltonen@nokia.com
To:   openfastpath@list.openfastpath.org

Last updated: 2017-01-16 11:02:07 +0100

## Bugzilla Comment ID: 226
Date: 2017-01-16 11:02:07 +0100
From: janne.peltonen@nokia.com

ofp_get_next_hop() returns a pointer to ofp_nh_entry but does
not guarantee for how long the returned pointer will be valid.
There is no mechanism that would protect next hop modification
and deletion from concurrent access by the forwarding code.

When the packet forwarding code is using an ofp_nh_entry
returned by ofp_get_next_hop, another thread may be processing
a configuration change that deletes or modifies the next hop.

Possible consequences of the bug include packets getting
forwarded to a wrong next hop or dropped during route changes.

**Comment by sovu** [comment]
First: The MTRIE structure is synchronized in itself and it does protect from write/delete of the same ofp_rtl_node node with a RCU like design pattern.

Second: An freed rtl_node is put at the end of the list of free available nodes for allocation. The data is available until it will be reallocated and overwritten, presumably after enough time.
Because it is at the end of the list the availability should be enough to use data and not reuse that pointer, in this case the content is valid.

In this case, instead of having a counter of usage for each rtl_node we put it at the end of the list, and the rtl_node will have a expiration time (depending on the lenght of the list and the remove/insert pattern)

The SIZE of the free list should be big enough for the cycling speed (remove/insert) of nodes.

In the end when an unexpected collision happens this is accepted, because we are using a small memory footprint and we trade the speed of not using locks with the consequence raised:
"Possible consequences of the bug include packets getting forwarded to a wrong next hop or dropped during route changes."

The only cave heat is when using a rtl_node pointer much after it was received and freed.
To fully avoid this we could have a usage counter per rtl_node and reuse it when counter is 0.

**Comment by sovu** [comment]
I quote Janne on what needs to be fixed on this issue:

1. documentation:
"It would be good to have such conscious design choices documented somehow,
e.g. as a couple of comments in strategic places in the code. Without that
the design choice is not distinguishable from a bug by looking at the code."

2. issue with the code not coresponding with actual design:
"the freed nodes (with or without MTRIE) are put in front
of the list. The node that was freed last is the one that gets allocated
first, so the length of the freelist does not matter."
