### ISSUE TITLE
Environment - virtual

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#21]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 21
Date: 2015-06-03 08:44:13 +0200
From: Bogdan Pricope &lt;<bogdan.pricope@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Last updated: 2015-06-03 08:44:13 +0200

## Bugzilla Comment ID: 26
Date: 2015-06-03 08:44:13 +0200
From: Bogdan Pricope &lt;<bogdan.pricope@enea.com>&gt;

Environment - virtual

**Comment by ViktorTikkanen** [comment]
Hi!

Can this issue be closed or are there any open questions regarding running OFP applications in virtual environments?

**Comment by sovu** [comment]
From: Tikkanen, Viktor (Nokia - FI/Espoo) 
Sent: Thursday, October 19, 2017 12:52 PM
To: 'Sorin Vultureanu' <Sorin.Vultureanu@enea.com>
Subject: RE: [openfastpath] issues #79 and #108

Hi Sorin!

Below are some points:

1. ODP/OFP can be compiled and run in virtual machines and containers without code changes. I used mostly following configurations:

- CentOS 7 based VMs deployed with Oracle's VirtualBox in Windows laptop
- CentOS 7 based VMs deployed by OpenStack in Linux servers (OPNFV reference HW configuration)
- gcc:4.9.4 based containers deployed by Docker in Linux servers (or even inside VMs)

2. Since ODP/OFP doesn't have control over physical NICs in native (without SR-IOV / PCI passthrough) virtual environments, performance is mostly limited by virtialization infrastructure (e.g. if VMs are located in different physical servers, performance numbers for VM <-> VM traffic can be tens times worse than in case of baremetal configuration).

3. Some functional limitations should be taken into account in virtual deployments. E.g. even if multiqueueing is enabled for virtio interfaces, they don't seem to support RSS hashing (causing problems for current nginx_ofp implementation in case of 3 and more worker threads). Also TCP checksum calculation is not always working as expected by OFP with default virtio settings.

-Viktor

some of those aspects are available in "Using OFP in virtualized environments and containers" chapter of the user guide.
