### ISSUE TITLE
Design of interaction between GRE, vxlan and IPSec needs to be rethought

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#96]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 96
Date: 2016-09-21 11:36:32 +0200
From: Dan Lilliehorn - Enea &lt;<dan.lilliehorn@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Last updated: 2016-09-21 11:36:32 +0200

## Bugzilla Comment ID: 182
Date: 2016-09-21 11:36:32 +0200
From: Dan Lilliehorn - Enea &lt;<dan.lilliehorn@enea.com>&gt;

**Comment by JannePeltonen** [comment]
The biggest problems and limitations regarding fragmentation of tunneled packets and regarding nested tunneling were fixed by the following commits:

fdb6f35 Do fragmentation before tunnel encapsulation.
5859c84 Recurse back to ofp_ip_output() after VxLAN encapsulation.
cc4df42 Recurse back to generic IP output after GRE encapsulation.

As the original complainer about the problems I think this is enough to close this issue even though there are certainly more cleanup opportunities in the code.
